services:
  resendpit:
    build:
      context: .
      dockerfile: Dockerfile.new
    ports:
      - "3000:3000"
    restart: unless-stopped
    environment:
      # - RESENDPIT_MAX_EMAILS=100
      - PORT=3000
